### ISSUE TITLE
CUDA not available despite correct libTorch and Nvidia Driver

### ISSUE THREAD

**Issue by Shinribo** [LaurentMazare/tch-rs#988]
OS: Win11
GPU: RTX4080 (CUDA 13.0 reported by Driver)

Using Python + Pytorch Cuda is available and used.
Using tch (v0.22) with libtorch-win-shared-with-deps-2.9.0+cu130 as per Readme/Libtorch Manual Install Cuda isnt usable.

Given that Cuda works with Python it seems like a error in tch or libtorch-win-shared-with-deps-2.9.0+cu130.

When i deleted libtorch-win-shared-with-deps-2.9.0+cu130 to rule out a corrupted install, tch complained about not beeing able to link to libtorch_cuda.so.

**Comment by Shinribo** [comment]
I am aware of some "hacks" descibed in some other related issues, however none of them are actually usable as they lack sufficient explanation and description for using them.

**Comment by seanpray** [comment]
Manually loading the CPU dynlib works for me, you can try that as a quick work around. I had the same thing with CUDA detected but not activating without this. You'll have to edit the path so that it points to the correct library on your system if you give it a shot.

```rs
let path = "/opt/libtorch/lib/libtorch_cpu.so";
let path_exists = PathBuf::from(&path).exists();
let path = CString::new(path).unwrap();
if path_exists {
    unsafe {
        dlopen(path.into_raw(), 1);
    }
}
```

**Comment by Shinribo** [comment]
> Manually loading the CPU dynlib works for me, you can try that as a quick work around. I had the same thing with CUDA detected but not activating without this. You'll have to edit the path so that it points to the correct library on your system if you give it a shot.
> 
> let path = "/opt/libtorch/lib/libtorch_cpu.so";
> let path_exists = PathBuf::from(&path).exists();
> let path = CString::new(path).unwrap();
> if path_exists {
>     unsafe {
>         dlopen(path.into_raw(), 1);
>     }
> }

i assume this goes into build.rs of my project? And where do i get "dlopen" from?

**Comment by seanpray** [comment]
This must be executed during runtime so it cannot be placed in build.rs, it should be in your main.rs or before you use anything that could need CUDA. dlopen is from the libc crate, this is to forcibly load the dynamic library at runtime. It may be the case you need to load multiple or a different file since you are on windows, such as libtorch_cuda.so instead of libtorch_cpu.so.

**Comment by Shinribo** [comment]
> This must be executed during runtime so it cannot be placed in build.rs, it should be in your main.rs or before you use anything that could need CUDA. dlopen is from the libc crate, this is to forcibly load the dynamic library at runtime. It may be the case you need to load multiple or a different file since you are on windows, such as libtorch_cuda.so instead of libtorch_cpu.so.

Using your code, modified to work on Windows throws a STATUS_ACCESS_VIOLATION

dlopen = "0.1.8"

let path = "C:\\Users\\Admin\\libtorch-win-shared-with-deps-2.9.0+cu130\\libtorch\\lib\\torch_cuda.dll";
    let path_exists = PathBuf::from(&path).exists();
    //let path = CString::new(path).unwrap();
    if path_exists {
        unsafe {
            dlopen::raw::Library::open(path).unwrap();
        }
    }

**Comment by mixaal** [comment]
I think here is the solution:  #984

**Comment by grizov-stelar** [comment]
Just for the next tortured soul in a death match to get cuda to show up, the dlopen solution is what finally worked for me after days of trying all the other hacks suggested here
